// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/dandynaufaldi/idy-go/domain/model"

// RatingRepository is an autogenerated mock type for the RatingRepository type
type RatingRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: rating, ideaID
func (_m *RatingRepository) Save(rating *model.Rating, ideaID *model.IdeaID) error {
	ret := _m.Called(rating, ideaID)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Rating, *model.IdeaID) error); ok {
		r0 = rf(rating, ideaID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
