// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "github.com/dandynaufaldi/idy-go/domain/entity"
import mock "github.com/stretchr/testify/mock"

import value "github.com/dandynaufaldi/idy-go/domain/value"

// RatingRepository is an autogenerated mock type for the RatingRepository type
type RatingRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: rating, ideaID
func (_m *RatingRepository) Save(rating *entity.Rating, ideaID *value.IdeaID) error {
	ret := _m.Called(rating, ideaID)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Rating, *value.IdeaID) error); ok {
		r0 = rf(rating, ideaID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
